spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost:9090/./egobooster
    username: egobooster
    password:
  mail:
    host: smtp.gmail.com
    port: 587
    username: my.egobooster@gmail.com
    password: wqowxzvgcoaudsbs
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
